### ISSUE TITLE
confused cmd

### ISSUE THREAD

**Issue by oldthreefeng** [joseluisq/docker-alpine-nginx-php7#1]
https://github.com/joseluisq/docker-alpine-nginx-php7/blob/39b83083b00cd897a7d5855cd546abe226a2206d/Dockerfile#L10-L11

why need L11?

**Comment by joseluisq** [comment]
Sorry but that's an old image no longer supported.
But instead please take a look at https://github.com/joseluisq/alpine-php-fpm
